services:
  api:
    build:
      context: ./src/backend
      dockerfile: Mediflow.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__SqlServer: Server=sqlserver;Database=MediflowDb;User Id=sa;Password=${SQLSERVER_SA_PASSWORD};TrustServerCertificate=True
      Jwt__Issuer: mediflow.api
      Jwt__Audience: mediflow.web
      Jwt__Secret: ${JWT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
      - redis

  web:
    image: node:24-alpine
    working_dir: /app
    volumes:
      - ./src/frontend/web:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - api

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SQLSERVER_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  objectstorage:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  sql_data:

