apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mediflow-production
resources:
  - ../../base
patches:
  - path: replicas.yaml
secretGenerator:
  - name: mediflow-api-secrets
    literals:
      - ASPNETCORE_ENVIRONMENT=Production
      - Jwt__Secret=replace-with-production-secret
      - ConnectionStrings__SqlServer=Server=sqlserver;Database=MediflowDb;User Id=sa;Password=replace-production-sql-password;TrustServerCertificate=True
generatorOptions:
  disableNameSuffixHash: true
